# Server configuration
server.port=8081
# H2 Database configuration
spring.datasource.url=jdbc:h2:file:./layered-crud-db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
# JPA and Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Enable H2 console
spring.h2.console.enabled=true
# Path to access H2 console
spring.h2.console.path=/h2-console
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
